itrader/urls.py
from django.urls import path
from . import views

app_name = 'itrader'
urlpatterns = [
    path('home', views.home, name='home'),
    path('itrader', views.itrader, name='itrader'),
    path('contactus', views.contactus, name='contactus'),
    path('aboutus', views.aboutus, name='aboutus'),
    path('buysell', views.buysell, name='buysell'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('news', views.news, name='news'),
    path('signup', views.signup, name='signup'),
    path('signin', views.signin, name='signin'),
    path('logout', views.logout, name='logout'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate'),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path('itrader/chat', views.chat, name='chat'),
    path('itrader/<str:roomname>/', views.room, name='room'),
]

trading/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views

app_name = 'itrader'

urlpatterns = [
    path('', include(('itrader.urls', 'itrader'), namespace='itrader')),
    path('admin/', admin.site.urls),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='itrader/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="itrader/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='itrader/password/password_reset_complete.html'), name='password_reset_complete'),  

]

itrader/models.py
from django.db import models
from django.conf import settings
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "trading.settings")

class StockData(models.Model):
    security = models.CharField(max_length=20, unique=True)
    lastprice= models.IntegerField()
    demandqty= models.IntegerField()
    demandprice= models.IntegerField()
    supplyprice= models.IntegerField()
    supplyqty= models.IntegerField()
    lastqty= models.IntegerField()
    high= models.IntegerField()
    low= models.IntegerField()

class Message(models.Model):
    username = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room = models.CharField(max_length=255)
    content = models.TextField()
    date_added = models.DateTimeField()

    class Meta:
        ordering = ('date_added',)

class Room(models.Model):
    # title = models.CharField(max_length=255, unique=True, blank=False,)
    title = models.ForeignKey(StockData, on_delete=models.CASCADE)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, help_text="users who are connected to the chat")

    def __str__(self):
        return self.title
    def connect_user(self,user):
        # return true if user is added to the list
        is_user_added = False
        if not user in self.users.all():
            self.users.add(user)
            self.save()
            is_user_added = True
        elif user in self.users.all():
            is_user_added = True
        return is_user_added
    def disconnect_user(self, user):
        # retur true if user is removed from the user list
        is_user_removed = False
        if not user in self.users.all():
            self.users.remove(user)
            self.save()
            is_user_removed = True
        return is_user_removed

    @property
    def group_name(self):
        # returns the channel name that sockets should subscribe to and get sent messages as they are generated
        return f"PublicChatRoom-{self.id}"



class Trade(models.Model):
    clientcode = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    buysell =  models.CharField(max_length=20)
    security =  models.ForeignKey(StockData, on_delete=models.CASCADE)
    market =  models.CharField(max_length=20)
    quantity =  models.IntegerField()
    price =  models.IntegerField()
    validupto =  models.DateField()
    delivery = models.CharField(max_length=20)
    dateplaced = models.DateTimeField(auto_now_add=True)

class News(models.Model):
    title = models.CharField(max_length=200)
    link = models.CharField(max_length=200)
    content =  models.TextField()
    date = models.DateField(max_length=200)
    sentimentscore = models.IntegerField()
class CompanyProfile(models.Model):
    security = models.CharField(max_length=20, unique=True)
    profile = models.TextField()

class CorporateAction(models.Model):
    security = models.CharField(max_length=20)
    action = models.TextField()
    date = models.CharField(max_length=200)

itrader/views.py
from django.shortcuts import redirect, render
from django.http.response import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout as django_logout
from django.contrib.auth.decorators import login_required
from urllib3 import HTTPResponse
from trading import settings
from django.core.mail import send_mail, EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from . tokens import generate_token
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.forms import PasswordResetForm
from django.db.models.query_utils import Q
import json, psycopg2
from .models import Message, Room, StockData, Trade, News, CompanyProfile
from django.contrib.auth.models import User


def home(request):
    return render(request, "itrader/home.html")

def contactus(request):
    return render(request, "itrader/contactus.html")

def aboutus(request):
    return render(request, "itrader/aboutus.html")

def news(request):
    
    news_articles = News.objects.order_by('-date')
    topics = StockData.objects.all()
    return render(request, 'itrader/news.html', {'news_articles': news_articles, 'topics':topics})

def dashboard(request):
    username = None
    if request.user.is_authenticated:
        username = request.user.username
    activetrades = Trade.objects.all()
    return render(request, "itrader/dashboard.html", {'username':username, 'activetrades':activetrades})

def room(request, roomname):
    username = None
    if request.user.is_authenticated:
        username = request.user.username
    rooms = StockData.objects.all()
    messages = Message.objects.order_by('room')
    return render(request, 'itrader/room.html', {'roomname': roomname, 'username':username, 'messages': messages, 'rooms':rooms})

def chat(request):
    username = None
    if request.user.is_authenticated:
        username = request.user.username
    rooms = StockData.objects.all()
    messages = Message.objects.all()
    return render(request, "itrader/chat.html", {'username':username, 'rooms':rooms, 'messages': messages})

def buysell(request):
    if request.method == "POST":
        username = request.POST['clientcode']
        buysell = request.POST['buysell']
        security = request.POST['security']
        market = request.POST['market']
        quantity = request.POST['quantity']
        price = request.POST['price']
        validupto = request.POST['validupto']
        delivery = request.POST['delivery']

        trade = Trade.objects.create(clientcode=User.objects.get(username= username), buysell=buysell, security=StockData.objects.get(security=security), market=market, quantity=quantity,price=price,validupto=validupto,delivery=delivery)
        trade.save()
        return render(request, "itrader/itrader.html")


def signin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST["password"]

        user = authenticate(username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('/itrader') 
        else: 
            messages.error(request, "Invalid Login")
    return render(request,  "itrader/auth.html")

def signup(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2= request.POST['password2']

        
        if User.objects.filter(username=username):
            messages.error(request, "Username already exist! Please try another username")
        elif User.objects.filter(email=email).exists():
            messages.error(request, "Email already registered")
        elif len(username)>20:
            messages.error(request, "Username must be less that 20 characters")
        elif password1 != password2:
            messages.error(request, "Passwwords didn't match")
        elif not username.isalnum():
            messages.error(request, "Username must be Alpha-numeric")
        else:
            user = User.objects.create_user(username, email, password1)
            user.is_active = False
            user.save()

            messages.success(request, "Your Account has been successfully created. We have sent you a confirmation email, please confirm your email address in order to activate your account.")

            #Welcome Email
            subject = "Welcome to iTrader"
            message = "Hello " + user.username + "! \n" + "Welcome to iTrader! \nWe have sent you a confirmation email, please confirm your email address in order to activate your account. \n \nThank you \niTrader"
            from_email = settings.EMAIL_HOST_USER
            to_list = [user.email]
            send_mail(subject, message, from_email, to_list, fail_silently=True)

            #Email Address confirmation
            current_site = get_current_site(request)
            email_subject = "Confirm your email!!"
            message2 = render_to_string("itrader/email_confirmation.html",{
                'name': user.username,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': generate_token.make_token(user)
            })
            email = EmailMessage(
                email_subject,
                message2,
                settings.EMAIL_HOST_USER,
                [user.email],
            )
            email.fail_silently = True
            email.send()

            return redirect("/signin")
    return render(request,  "itrader/auth.html") 

@login_required
def logout(request):
    django_logout(request)
    return redirect('/home')

def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotEXist):
        user = None
    
    if user is not None and generate_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return render(request, "itrader/itrader.html") 
    else:
        return render(request, 'itrader/activation_failed.html')

def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    current_site = get_current_site(request)
                    email_subject = "Password Reset Requested"
                    reset_message = render_to_string("itrader/password/password_reset_email.txt",{
                        'name': user.username,
                        'domain': current_site.domain,
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    })
                    email = EmailMessage(
                        email_subject,
                        reset_message,
                        settings.EMAIL_HOST_USER,
                        [user.email],
                    )
                    email.fail_silently = True
                    email.send()
                    return redirect ("/password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="itrader/password/password_reset.html", context={"password_reset_form":password_reset_form})

def itrader(request):
    username = None
    if request.user.is_authenticated:
        username = request.user.username
    try:
        #connect to the db
        con = psycopg2.connect(
            host = 'localhost',
            database = 'trading',
            user = 'postgres',
            password = 'postgres',
            port = 5432
        )

        #cursor
        cur = con.cursor()
        #execute querys
        cur .execute("select array_to_json(array_agg(row_to_json(stockdata))) from(select security,lastprice,demandqty,demandprice, supplyprice,supplyqty,lastqty,high,low from itrader_stockdata) stockdata")
        data = cur.fetchone()
        data = json.dumps(data[0])
        cur.execute("select array_to_json(array_agg(row_to_json(companyprofile))) from(select security,profile from itrader_companyprofile) companyprofile")
        profile = cur.fetchone()
        profile = json.dumps(profile[0])
        cur.execute("select array_to_json(array_agg(row_to_json(corporateaction))) from(select security,action,date from itrader_corporateaction) corporateaction")
        action = cur.fetchone()
        action = json.dumps(action[0])
        cur.execute("select array_to_json(array_agg(row_to_json(equity))) from(select sentimentscore from itrader_news where content LIKE '%equity%') equity")
        equity = cur.fetchone()
        equity = json.dumps(equity[0])
        
        #close cursor
        cur.close()  
        return render(request, "itrader/itrader.html",  {'data': data, 'username':username, 'profile':profile,'action':action,'equity':equity})
    except:
       return('Error Connecting') 
    finally:
        #close the connection
        con.close()  

itrader/templates/itrader/aboutus.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="UTF-8">
        <title> iTrader </title>
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
        <!-- <link rel="stylesheet" type="text/css" href="{% static 'itrader/css/home.css' %}"> -->
        <link rel="stylesheet" type="text/css" href="{% static 'itrader/css/aboutus.css' %}">
            <meta name= "viewport" content="width=device-width, initial-scale=1.0">
    </head>
<body>
    <div class="banner">
        
    <div class="section">
        <div class="navbar">
            <div class="logo_content">
                <div class="logo">
                    <i class='bx bx-line-chart'></i>
                    <div class="logo_name">iTrader</div>
                </div>
            </div>
           <ul>
               <li><a href="home"> Home </a></li>
               <li><a href="aboutus"> About  </a> </a></li>
               <li><a href="contactus"> Contact Us </a></li>
           </ul>
        </div> 
        <div class="container">

            <div class="content-section">
                <div class="title">
                    <h1>About Us</h1>
                </div>
                <div class="content">
                    <h3>iTrader the trading platform you need</h3>
                    <p>iTrader is an all in one trading platform. You can place your trades, check the latest news and chat with other traders. In addition to that we provide market analysis.</p>
                    <div class="button">
                        <span></span>
                        <a href=""> Read More</a>
                    </div>
                </div>
                <div class="social">
                    <a href=""><i class='fab fa-facebook'></i></a>
                    <a href=""></a><i class='fab fa-twitter'></i></a>
                    <a href=""></a><i class='fab fa-instagram'></i></a>
                </div>
            </div>
            <div class="image-section">
                <img src="{% static 'itrader/images/pexels-photo-1229861.jpeg' %}">
            </div>
        </div>
    </div>
</body>
</html>

itrader/templates/itrader/activation_failed.html
{% autoescape off %}
Activation failed, please try again.
{% endautoescape %} 

itrader/templates/itrader/auth.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="UTF-8">
        <title> iTrader | Login </title>
        <link rel="stylesheet" type="text/css" href="{% static 'itrader/css/auth.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
            <meta name= "viewport" content="width=device-width, initial-scale=1.0">
    </head>
<body>
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message | safe }}
    </div>
    {% endfor %}
    
    <div class="container">
        <input type="checkbox" id="flip">
        <div class="cover">
            <div class="front">
                <img src="{% static 'itrader\images\istockphoto-1332377628-170667a.jpg' %}" alt="">   
                <div class="text">
                    <span class="text-1">This plaform is built to increase accessibility to stockbrokerage services.</span>
                    <span class="text-2">Let's get Trading</span>
                </div>
            </div>
            <div class="back">
                <img class="backImg" src="{% static 'itrader\images\istockphoto-1332377628-170667a.jpg' %}" alt="">   
                <div class="text">
                    <span class="text-1">This plaform is built to increase accessibility to stockbrokerage services.</span>
                    <span class="text-2">Let's get Trading</span>
                </div>
            </div>
        </div>
        <div class="forms">
            <div class="form-content">
                <div class="login-form">
                    <div class="title">Sign In</div>
                <form action="{% url 'itrader:signin' %}" method="post">
                {% csrf_token %}
                    <div class="input-boxes">
                        <div class="input-box">
                            <i class='bx bxs-user'></i>   
                            <input type="text" name="username" placeholder="User Name" required>
                        </div>
                        <div class="input-box">
                            <i class='bx bxs-lock-alt'></i>
                            <input type="password" name="password" placeholder="Password" required>
                        </div>
                        <div class="text"><a href="/password_reset">Forgot password?</a></div>
                        <div class="button input-box">
                            <input type="submit" value="Sign In">
                        </div>
                        <div class="text sign-up-text"> Don't have an account? <label for="flip">Sign Up now</label></label></div>
                    </div>
                </form>
            </div>    
            <div class="signup-form">
                <div class="title">Signup</div>
            <form action="/signup" method="post">
            {% csrf_token %}
                <div class="input-boxes">
                    <div class="input-box">
                        <i class='bx bxs-user'></i>
                        <input type="text" name="username" placeholder="Username" required>
                    </div>
                    <div class="input-box">
                        <i class='bx bxs-envelope' ></i>
                        <input type="email" name="email" placeholder="Email Address" required>
                    </div>
                    <div class="input-box">
                        <i class='bx bxs-lock-alt'></i>
                        <input type="password" name="password1" placeholder="Password" required>
                    </div>
                    <div class="input-box">
                        <i class='bx bxs-lock-alt'></i>
                        <input type="password" name="password2" placeholder="Confirm Password" required>
                    </div>
                    <div class="button input-box">
                        <input type="submit" value="Sign Up">
                    </div>
                    <div class="text sign-up-text">Already have an account? <label for="flip">Sign In now</label></label></div>
                </div>
            </form>
            </div>
         </div>
    </div>
   </body>
</html>

itrader/templates/itrader/chat.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="UTF-8">
        <title> iTrader </title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.7.0/moment.min.js" type="text/javascript"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'itrader/css/itrader.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'itrader/css/room.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
        <script src="https://unpkg.com/ag-grid-community/dist/ag-grid-community.min.noStyle.js"></script>
        <link rel="stylesheet" href="https://unpkg.com/ag-grid-community/dist/styles/ag-grid.css">
        <link rel="stylesheet" href="https://unpkg.com/ag-grid-community/dist/styles/ag-theme-balham.css">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
            <meta name= "viewport" content="width=device-width, initial-scale=1.0">
    </head>
<body>
<!-- side Nav Bar -->
<div class = "sidebar">
    <div class="logo_content">
        <div class="logo">
            <i class='bx bx-line-chart'></i>
            <div class="logo_name">iTrader</div>
        </div>
        <i class='bx bx-menu' id="btn"></i>
    </div>
    <ul class="nav_list">
        <li>
            <i class='bx bx-search-alt' ></i>
            <input type="text" placeholder="Search...">
            <span class="tooltip">Search...</span>
        </li> 
        <li>
            <a href="itrader" data-bs-toggle="tooltip" title="Watchlist" >
                <i class='bx bx-stopwatch'></i>
                <span class="links_name">Watchlist</span>
            </a>
            <span class="tooltip">Watchlist</span>
        </li>
        <li>
            <a href="dashboard">
                <i class='bx bx-grid-alt' ></i>
                <span class="links_name">Dashboard</span>
            </a>
            <span class="tooltip">Dashboard</span>
        </li>
        <li>
            <a href="news">
                <i class='bx bx-news' ></i>
                <span class="links_name">News</span>
            </a>
            <span class="tooltip">News</span>
        </li>
        <li>
            <a href="itrader/chat">
                <i class='bx bx-message-rounded-dots' ></i>
                <span class="links_name">Chat</span>
            </a>
            <span class="tooltip">Chat</span>
        </li>
    </ul>
      <div class="profile_content">
          <div class="profile">
              <div class="profile_details">
                  <img src="{% static 'itrader\images\alex-starnes-PK_t0Lrh7MM-unsplash.jpg' %}" alt="">
                  <div class="name_job">
                      <!-- {% if user.is_authenticated %} -->
                      <div class="username" id="username">{{ username}}</div>
                      <!-- {% endif %} -->
                  </div>
              </div>
              <a href="/logout"><i class='bx bx-log-out' id="log_out"></i></a>
          </div>
      </div>
  </div>
  <div class="home_content">
    <section class="section" style="height:100%;">
      <div class="container" style="height:100%;">
      <div class="row clearfix" style="height:100%;">
          <div class="col-lg-12">
              <div class="card chat-app" style="height:85vh;">
                  <div id="plist" class="people-list">
                      <div class="input-group">
                          <div class="input-group-prepend">
                              <span class="input-group-text"><i class="fa fa-search"></i></span>
                          </div>
                          <input type="text" class="form-control" placeholder="Search...">
                      </div>
                      <ul class="list-unstyled chat-list mt-2 mb-0" style="overflow: auto; max-height:90vh; height: 90%;">
                          {% for r in rooms %}
                          <li class="clearfix" id="room-name-submit">
                              <div class="about">
                                  <div class="name" >{{ r.security }}</div>
                              </div>
                          </li>
                          {% endfor %}
                                   
                      </ul>
                  </div>
                  <div class="chat" style="height:80vh;">
                      <div class="chat-header clearfix">
                          <div class="row">
                              <div class="col-lg-6">
                                  <a href="javascript:void(0);" data-toggle="modal" data-target="#view_info">
                                  </a>
                                  <div class="chat-about">
                                      <h6 class="m-b-0">{{ username }}</h6>
                                  </div>
                              </div>
                              <div class="col-lg-6 hidden-sm text-right">
                                  <a href="javascript:void(0);" class="btn btn-outline-secondary"><i class="fa fa-camera"></i></a>
                                  <a href="javascript:void(0);" class="btn btn-outline-primary"><i class="fa fa-image"></i></a>
                              </div>
                          </div>
                      </div>
                      <div class="chat-history" id="chat-messages" style="height:80%; overflow-y:scroll;">
                        {% for m in messages %}
                          <ul class="m-b-0">
                              <li class="clearfix">
                                    <div class="message-data text-right">
                                      <span class="message-data-time">{{ m.username}}</span>
                                      <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="avatar">

                                    </div>
                                    <div class="message other-message float-right"> 
                                      {{ m.content }} <br>
                                      <span class="message-data-time">{{m.date_added}}</span>
                                    </div>
                              </li>
                              <li class="clearfix">
                                  <div class="message-data">
                                      <span class="message-data-time">{{ m.username}}</span>
                                      <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="avatar">

                                  </div>
                                  <div class="message my-message">
                                      {{ m.content }} <br>
                                      <span class="message-data-time">{{m.date_added}}</span>

                                  </div>                                    
                              </li>                               
                          </ul>
                        {% endfor %}
                      </div>
                      <!-- <div class="chat-message clearfix">
                          <div class="input-group mb-0">
                              <div class="input-group-prepend" id="chat-message-submit"> 
                                  <span class="input-group-text" ><i class="fa fa-send"></i></span>
                              </div>
                              <input type="text" class="form-control" id="chat-message-input" placeholder="Enter text here...">                                    
                          </div> -->
                      </div>
                  </div>
              </div>
          </div>
      </div>
      </div>
    </section>
  </div>
<script>
    jQuery(function(){
        $('div.name').click(function() {
            var roomname = $(this).text();
            var userName =  $(username).text();
            window.location.replace(roomname + '/?username=' + userName);
        })
    });
  </script>
  <script src="{% static 'itrader/js/script.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

itrader/templates/itrader/email_confirmation.html
{% autoescape off %}

Welcome to iTrader
Hello {{ name }}

Please confirm your email by clicking on the following link.

Confirmation Link: http://{{domain}}{% url 'itrader:activate' uidb64=uid token=token %}

{% endautoescape %} 